#!/usr/bin/env bash
alias emm="sudo emerge --ask"
alias vi=nvim
alias vim=nvim
alias svim="sudo -E nvim"







PATH="$PATH:$HOME/.GO/bin"
# place ''~/.bashrc''

# added by travis gem
[ -f /home/pallav/.travis/travis.sh ] && source /home/pallav/.travis/travis.sh
