#!/usr/bin/env bash
alias emm="sudo emerge --ask"
alias vi=nvim
alias vim=nvim
alias svim="sudo -E nvim"

export PATH="$PATH:$HOME/.GO/bin"
source /usr/share/nvm/init-nvm.sh

if [ -z "${NOZSH}" ] && type zsh &> /dev/null
then
    export SHELL=$(which zsh)
    if [[ -o login ]]
    then
        exec zsh -l
    else
        exec zsh
    fi
fi

# place ''~/.bashrc''
